from tkinter import *
window=Tk()
window.title("Area Calculator")
window.geometry("300x300")
label=Label(window,text="CALCULATOR")
label.grid(row=0,column=1)
label1=Label(window,text="Enter value 1")
label1.grid(row=1,column=0,padx=5,pady=10)
label2=Label(window,text="Enter value 2")
label2.grid(row=2,column=0,padx=5,pady=10)
value1=IntVar()
value2=IntVar()
textbox1=Entry(window,textvariable=value1)
textbox1.grid(row=1,column=1)
textbox2=Entry(window,textvariable=value2)
textbox2.grid(row=2,column=1)
def add():
    a=value1.get()+value2.get()
    label3.config(text="Result ="+str(a))
def sub():
    s=value1.get()-value2.get()
    label3.config(text="Result ="+str(s))
def mul():
    m=value1.get()*value2.get()
    label3.config(text="Result ="+str(m))
def div():
    d=value1.get()/value2.get()
    label3.config(text="Result ="+str(d))
button1=Button(window,text="-",command=sub)
button1.grid(row=3,column=1,pady=20,sticky=NW)
button2=Button(window,text="+",command=add)
button2.grid(row=3,columnspan=1,pady=20,sticky=N )
button3=Button(window,text="x",command=mul)
button3.grid(row=3,column=1,pady=20,sticky=E)
button4=Button(window,text="/",command=div)
button4.grid(row=3,column=1,pady=20,sticky=S)
label3=Label(window,fg="green")
label3.grid(row=4,column=1)
window.mainloop() 